version: 3

tasks:
  lint-fix:
    desc: Go 代码检查并自动修复
    cmd: golangci-lint run --fix

  lint:
    desc: Go 代码检查
    cmd: golangci-lint run

  test-e2e:tencent-cloud-cos:
    env:
      - E2E_S3_CONFIG=./secrets/e2e-tencent-cloud-cos.json
    desc: E2E 测试 (腾讯云 COS)
    cmd: go test -v -race ./s3
      
  test-e2e:aliyun-oss:
    env:
      - E2E_S3_CONFIG=./secrets/e2e-aliyun-oss.json
    desc: E2E 测试 (阿里云 OSS)
    cmd: go test -v -race ./s3
