version: 3

tasks:
  lint-fix:
    desc: Go 代码检查并自动修复
    cmd: golangci-lint run --fix

  lint:
    desc: Go 代码检查
    cmd: golangci-lint run

  test-e2e:tencent-cloud-cos:
    env:
      E2E_S3_CONFIG: '{{joinPath .ROOT_DIR "secrets/e2e-tencent-cloud-cos.json" }}'
    desc: E2E 测试 (腾讯云 COS)
    cmd: go test -v ./s3

  test-e2e:aliyun-oss:
    env:
      E2E_S3_CONFIG: '{{joinPath .ROOT_DIR "secrets/e2e-aliyun-oss.json" }}'
    desc: E2E 测试 (阿里云 OSS)
    cmd: go test -v ./s3

  test-e2e:cloudflare-r2:
    env:
      E2E_S3_CONFIG: '{{joinPath .ROOT_DIR "secrets/e2e-cloudflare-r2.json" }}'
    desc: E2E 测试 (腾讯云 COS)
    cmd: go test -v ./s3

  test-e2e:minio:
    env:
      E2E_S3_CONFIG: '{{joinPath .ROOT_DIR "e2e/minio/config.json" }}'
    desc: E2E 测试 (MinIO)
    cmds:
      - docker compose -f e2e/minio/docker-compose.yaml up -d
      - defer: docker compose -f e2e/minio/docker-compose.yaml down
      - go test -v ./s3
